name: Trigger the preview build in tailpipe.io

on:
  workflow_dispatch:

  push:
    branches-ignore: 
      - "main"

  pull_request:
    types: [opened]

jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
          repository: turbot/tailpipe.io
          event-type: build-preview-test
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "ref_name": "${{ github.ref_name }}"}'


  comment-link:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    steps:
      - name: Get the deployment details
        id: get_deployment_details
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
        uses: actions/github-script@v6
        with:
          script: |
            const branchName = 'docs/${{ github.event.pull_request.head.ref }}';

            const response = await fetch('https://tailpipe-io.vercel.app/api/deploy-details', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({ branch: branchName }),
            });
            if (!response.ok) {
              core.setOutput('foundDeployment', false);
            } else {
              const data = await response.json();
              core.setOutput('foundDeployment', true);
              core.setOutput('apiResponse', data);
            }

      - name: Add comment with preview link
        uses: actions/github-script@v7
        if: ${{ steps.get_deployment_details.outputs.foundDeployment == 'true' }}
        with:
          script: |
            const apiResponse = ${{ steps.get_deployment_details.outputs.apiResponse }};

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview link: [https://${apiResponse.meta.branchAlias}](https://${apiResponse.meta.branchAlias})`
            })